version: "3.7"
services:
  emp_service:
    build: .
    restart: always
    ports:
      - 8089:8080
    depends_on:
      - mysql_db
    command: sh -c './wait-for mysql_db:3306 --npm start'
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: shiva
      MYSQL_PASSWORD: Shiva@280
      MYSQL_ROOT_PASSWORD: Shiva@280
    
     